### ISSUE TITLE
Ressourcen, Benutzer & deren Beziehungen beschreibbar machen

### ISSUE THREAD

**Issue by niklashaug** [peerigon/access-control-testing#8]
Der Tool-User soll in der Lage sein, die vorhandenen Ressourcen, Benutzer und Beziehungen zu beschreiben.

Pseudo-Code:
```ts
const user1 = new User("user1", "password");
const user2 = new User("user2", "password");
const adminUser1 = new User("admin", "admin");

// second parameter is the authorization matrix, maps access types to required privileges
const todoResource = new Resource("Todo", {
  create: Privilege.CREATOR || Privilege.OWNER,
  read: Privilege.VIEWER || Privilege.OWNER,
  update: Privilege.EDITOR || Privilege.OWNER,
  delete: Privilege.OWNER, // OWNER is default for each access type
});
```

Diese sollen mit Ressourcen in der OpenApi Routen-Definition verknüpfbar sein:
```yaml
  /admin/users/{id}:
    get:
      summary: Einzelner Benutzer
      description: Gibt einen spezifischen Benutzer anhand der ID zurück.
      parameters:
        - name: id
          in: path
          required: true
          description: User-ID
          schema:
            type: integer
            example: 1
          x-act:
            resource-name: User
            resource-access: read
```

Es müssen also zusätzlich `resource-name` und `resource-access` aus den Parametern der Spezifikation ausgelesen werden, um das Mapping zu machen.
